--------------------------------------------------------
--  File created - Release  4.3    
--------------------------------------------------------

CREATE TABLE ACQUIRER_SETTLEMENTS 
(
  CREDIT_CARD_NUMBER VARCHAR2(16 BYTE) NOT NULL
 , ORDER_DATE VARCHAR2(45 BYTE) NOT NULL
 , AMOUNT VARCHAR2(16 BYTE) NOT NULL
 , MCC_CODE VARCHAR2(16 BYTE) NOT NULL
 , TERMINAL_ID VARCHAR2(16 BYTE) NOT NULL  
 , TRANSACTION_REF VARCHAR2(16 BYTE) NOT NULL
 , MODE_OF_PAYMENT VARCHAR2(16 BYTE) NOT NULL 
 , META_JOB_ID NUMBER(20, 0) NOT NULL 
 , META_JOB_START_TIME VARCHAR2(100 BYTE) NOT NULL 
 , META_PROCESSING_FILE VARCHAR2(100 BYTE) NOT NULL 
 , META_ACQUIRER VARCHAR2(20 BYTE) NOT NULL 
 , META_CHUNK_COMMIT_SIZE NUMBER(20, 0) NOT NULL 
);

CREATE TABLE CONFIGURATION_PARAMETERS 
(
  KEY VARCHAR2(100 BYTE) 
, VALUE VARCHAR2(100 BYTE) 
);

